/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#ffffff",
        "surface-container-lowest": "#000000",
        "on-surface": "#ffffff",
        "primary-container": "#c1121f",
        "tertiary-fixed-dim": "#ffffff",
        "inverse-primary": "#c1121f",
        "surface-tint": "#c1121f",
        "inverse-on-surface": "#000000",
        "surface": "#000000",
        "on-tertiary-fixed-variant": "#ffffff",
        "on-tertiary-container": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#ffffff",
        "surface-variant": "#000000",
        "background-matte": "#000000",
        "surface-container-highest": "#1a1a1a",
        "on-error": "#ffffff",
        "error": "#c1121f",
        "secondary": "#ffffff",
        "background": "#000000",
        "on-error-container": "#ffffff",
        "primary-fixed": "#c1121f",
        "on-secondary-container": "#ffffff",
        "error-container": "#c1121f",
        "surface-container": "#1a1a1a",
        "surface-dim": "#000000",
        "secondary-fixed-dim": "#ffffff",
        "on-surface-variant": "#ffffff",
        "tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#000000",
        "on-secondary-fixed": "#000000",
        "on-secondary": "#000000",
        "surface-bright": "#1a1a1a",
        "secondary-fixed": "#ffffff",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#ffffff",
        "surface-container-low": "#1a1a1a",
        "outline-variant": "#ffffff",
        "rule-white": "rgba(255, 255, 255, 0.08)",
        "text-muted": "#ffffff",
        "on-primary-container": "#ffffff",
        "secondary-container": "#1a1a1a",
        "on-primary-fixed": "#ffffff",
        "on-secondary-fixed-variant": "#ffffff",
        "surface-container-high": "#1a1a1a",
        "inverse-surface": "#ffffff",
        "primary": "#c1121f",
        "primary-fixed-dim": "#c1121f",
        "on-background": "#ffffff",
        "netflix-red": "#e50914",
      },
      spacing: {
        "margin-desktop": "80px",
        "max-width": "1440px",
        "margin-mobile": "24px",
        "gutter": "32px",
        "unit": "8px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "ui-sans-serif", "system-ui", "sans-serif"],
        evelins: ["'Evelins'", "serif"],
      },
    }
  },
  plugins: []
};